name: Deploy React App to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Change to frontend directory
        run: cd frontend

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build
        run: |
          cd frontend
          npm run build
        env:
          CI: false

      - name: Deploy to S3
        uses: reggionick/s3-deploy@v3
        with:
          folder: frontend/build
          bucket: ${{ secrets.bucket }}
          bucket-region: ${{ secrets.region }}
          dist-id: ${{ secrets.id }}
          invalidation: /
          delete-removed: true
          no-cache: true
          private: true
